
#alias
alias 'll'='ls -l'
alias -- '-'='cd -'
alias '..'='cd ..'
alias 'e'='exit'
alias 'gs'='git status'
alias 'gaa'='git add .'
alias 'gcm'='git commit -m'
alias 'gco'='git checkout'
alias 'gb'='git branch -vvv'
alias 'gd'='git diff'
alias 'cls'='clear'
alias -- --='git checkout -'
alias 'show'='git show'
alias 'push'='git push origin '
alias 'fpush'='git push -f origin '
alias 'pull'='git pull origin '
alias 'rpull'='git pull origin  --rebase'
alias 'ml'='git log --author=chuchu-z'
alias 'gl'='git log'
alias 'ggl'='git log --graph'
alias 'gglp'='git log --graph --pretty=oneline --abbrev-commit'
alias 'lognu'='git log --pretty='%aN' | sort | uniq -c | sort -k1 -n -r'
alias 'qq'='review "git checkout"'
alias 'review'='review() { git status --short | egrep ^*.php | sed "s/^ *//" | egrep ^[^D] | tr -s " " | cut -d" " -f 2 | egrep -v database/migrations | xargs $1;};review'
alias dff='df -hl'
alias duh='duh() { du -h --max-depth=$1; }; duh'
alias vz='vim .zshrc'
alias sz='source .zshrc'
alias 'rsa'='cat ~/.ssh/id_rsa.pub'
